version: '3.8'

services:
  redbot:
    build: ./red
    image: registry.hosted-domains.com/shane/red-discord:${VERSION}
    env_file: ${ENV_FILE}
    volumes:
      - data_dir:/data
    deploy:
      replicas: 1
    networks:
      - carl-web-network

networks:
  carl-web-network:
    name: "${ENV_NAME}_cssnr-carlbot-web_default"
    external: true

volumes:
  data_dir:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_HOST},rw"
      device: ":/data/docker/${NFS_DIRECTORY}"
