version: "3.8"

services:
  redbot:
    build: ./red
    image: cssnr-carlbot-red:latest
    restart: always
    env_file: settings.env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "3.0"
          memory: 1G
    volumes:
      - /data/docker/red:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - redis
    networks:
      - cssnr-carlbot-internal

  redis:
    image: redis:6-alpine
    restart: always
    command: "redis-server --appendonly yes"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 25M
    volumes:
      - redis_data:/data
    networks:
      - cssnr-carlbot-internal

volumes:
  redis_data:

networks:
  cssnr-carlbot-internal:
    name: "${ENV_NAME:-local}-cssnr-carlbot-internal"
    driver: overlay
    attachable: true
