version: '3.7'

services:
  redbot:
    build:
      context: ./red
      network: host
    image: ${REGISTRY_HOST}/shane/cssnr-carlbot-red:${VERSION}
    restart: always
    env_file: ${ENV_FILE}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '3.0'
          memory: 1G
    volumes:
      - /data/docker/${STACK_NAME}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - redis
    networks:
      - cssnr-carlbot-internal
      - postgres

  redis:
    image: redis:6-alpine
    restart: always
    command: "redis-server --appendonly yes"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 50M
    volumes:
      - redis_data:/data
    networks:
      - cssnr-carlbot-internal

volumes:
  redis_data:

networks:
  cssnr-carlbot-internal:
    name: "${ENV_NAME}-cssnr-carlbot-internal"
    driver: overlay
    attachable: true
  postgres:
    external: true
