version: "3.8"

services:
  redbot:
    build: ./red
    image: ghcr.io/cssnr/carlbot-red:${VERSION:?err}
    restart: always
    environment:
      BOT_NAME: ${BOT_NAME}
      BOT_PREFIX: ${BOT_PREFIX}
      BOT_TOKEN: ${BOT_TOKEN}
      TZ: ${TZ}
      STORAGE_TYPE: ${STORAGE_TYPE}
      PGHOST: ${PGHOST}
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      PGDATABASE: ${PGDATABASE}
      PGPASSWORD: ${PGPASSWORD}
      DEBUG: ${DEBUG}
      CO_OWNER: ${CO_OWNER}
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "3.0"
          memory: 1G
    volumes:
      - /data/docker/${STACK_NAME:?err}:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - redis
    networks:
      - cssnr-carlbot-internal
      - postgres

  redis:
    image: redis:6-alpine
    restart: always
    command: "redis-server --appendonly yes"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 25M
    volumes:
      - redis_data:/data
    networks:
      - cssnr-carlbot-internal

volumes:
  redis_data:

networks:
  cssnr-carlbot-internal:
    name: "${ENV_NAME:?err}-cssnr-carlbot-internal"
    driver: overlay
    attachable: true
  postgres:
    external: true
