version: '3.7'

services:
  redbot:
    build:
      context: ./red
      network: host
    image: shane-cssnr-carlbot-red:latest
    restart: always
    env_file: settings.env
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '3.0'
          memory: 1G
    volumes:
      - /data/docker/red:/data
    depends_on:
      - redis
    networks:
      - redbot-internal

  redis:
    image: redis:6-alpine
    restart: always
    command: "redis-server --appendonly yes"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 50M
    volumes:
      - redis_data:/data
    networks:
      - redbot-internal

volumes:
  redis_data:

networks:
  cssnr-carlbot-internal:
    name: "${ENV_NAME:-local}-cssnr-carlbot-internal"
    driver: overlay
    attachable: true
