version: '3.8'

services:
  redbot:
    build: ./red
    image: registry.hosted-domains.com/shane/red-discord:${VERSION}
    env_file: ${ENV_FILE}
    volumes:
      - data_dir:/data
    deploy:
      replicas: 1
    networks:
      - dev-cssnr-carlbot-internal

networks:
  dev-cssnr-carlbot-internal:
    external: true

volumes:
  data_dir:
    driver: local
    driver_opts:
      type: nfs
      o: "addr=${NFS_HOST},rw"
      device: ":${NFS_DIRECTORY}"
