version: '3.9'

services:
  redbot:
    build: ./red
    image: red-discord:latest
    env_file: settings.env
    volumes:
      - /data/docker/red:/data
    deploy:
      replicas: 1

  redis:
    image: redis:6-alpine
    command: "redis-server --appendonly yes"
    deploy:
      replicas: 1
    volumes:
      - redis_data:/data

volumes:
  redis_data:
